Code cleanup with bashate and shellcheck

diff --git a/bin/daps-xmlformat b/bin/daps-xmlformat
--- a/bin/daps-xmlformat
+++ b/bin/daps-xmlformat
@@ -17,9 +17,8 @@ CONFIG_FILE="/etc/daps/docbook-xmlformat.conf"
 echo "Using config file '$CONFIG_FILE'"
 
 if [ ! -e $CONFIG_FILE ]; then
-  echo "Could not find config file '$CONFIG_FILE'"
-  echo
-  exit 100
+    echo -e "Could not find config file '$CONFIG_FILE'\n"
+    exit 100
 fi
 
 #cmd="xmlformat.pl --config-file '$CONFIG_FILE' $@"
@@ -28,19 +27,18 @@ fi
 
 res=$(which xmlformat.pl 2>/dev/null)
 if [ "$res" = '' ]; then
-  echo "The xmlformat.pl script is missing. Please install the package xmlformat!"
-  echo
-  exit 200
+    echo -e "The xmlformat.pl script is missing. Please install the package xmlformat!\n"
+    exit 200
 fi
 
 xmlformat=$res
 ## check, if xmlformat supports tag-formatting
 if $xmlformat -t < /dev/null >/dev/null 2>&1; then
-  xmlformat="$xmlformat -t"
+    xmlformat="$xmlformat -t"
 else
-  echo "$xmlformat: tag-formatting not supported."
-  echo "Please install version 1.04.01 or later."
+    echo "$xmlformat: tag-formatting not supported."
+    echo "Please install version 1.04.01 or later."
 fi
 
-$xmlformat --config-file "$CONFIG_FILE" $@
+$xmlformat --config-file "$CONFIG_FILE" "$@"
 exit $?
