Fixes on echo statements. All warnings and errors now go to STDERR
git-svn-id: svn+ssh://svn.code.sf.net/p/daps/svn/trunk/daps@441 2c1a2506-8097-4b87-b405-3e90b480097b

diff --git a/bin/daps b/bin/daps
--- a/bin/daps
+++ b/bin/daps
@@ -568,8 +568,8 @@ fi
 # Now that we have the subcommand, check whether it is valid
 
 if [[ -z ${SUBCOMMANDS[$SUBCMD]} ]]; then
-    ccecho "error" "Error: Unknown subcommand \"$SUBCMD\""
-    ccecho "normal" "Type '$ME help' to get a list of global parameters and subcommands"
+    ccecho "error" "Error: Unknown subcommand \"$SUBCMD\"" >&2
+    ccecho "normal" "Type '$ME help' to get a list of global parameters and subcommands" >&2
     exit 1;
 fi
 
