Added proper help texts for sub commands
git-svn-id: svn+ssh://svn.code.sf.net/p/daps/svn/trunk/daps@1369 2c1a2506-8097-4b87-b405-3e90b480097b

diff --git a/bin/daps.in b/bin/daps.in
--- a/bin/daps.in
+++ b/bin/daps.in
@@ -186,7 +186,7 @@ USER_CONFIG="$HOME/.daps/config"
 
 declare -A SUBCOMMANDS
 SUBCOMMANDS=(
-    [all]=build_pdf
+    [all]=build_pdfs
     [bigfile-reduced]=build_generic
     [bigfile]=build_generic
     [check]=no_opts
@@ -265,8 +265,9 @@ SUBCOMMANDS=(
     [showenv]=show_env
     [showvariable]=profile_first
     [text]=build_generic
-    [txt-name]=show_names
+    [text-name]=show_names
     [txt]=build_generic
+    [txt-name]=show_names
     [validate]=comments_remarks
     [warn-images]=filelists
     [webhelp]=webhelp
@@ -275,6 +276,107 @@ SUBCOMMANDS=(
     [wiki]=build_generic
     [xmlgraphics-bw]=filelists
     [xmlgraphics]=filelists
+)
+
+#---------------------------------------------------
+# HELP texts for subcommands
+#
+# Associative array with
+#  Key   = subcommand
+#  Value = help text
+# 
+
+declare -A HELP_SUBCOMMAND
+HELP_SUBCOMMAND=(
+    [all]="Build a color PDF document from the XML sources."
+    [bigfile-reduced]="Creates a single XML file (bigfile) from the MAIN-file referenced in the\nDC-file or specified on the command line starting at the given rootid\nby following all xi:includes."
+    [bigfile]="Creates a single XML file (bigfile) from the MAIN-file referenced in the\nDC-file or specified on the command line by following all xi:includes.\nA rootid parameter is ignored."
+    [check]="DEBUGGING: Shows a list of internal variables and their values."
+    [checklink]="Validates ftp and http(s) links in XML sources."
+    [chklink]="Validates ftp and http(s) links in XML sources."
+    [clean-all]="Removes all data (documents, images, logfiles, profiled XML, ...) generated\nby DAPS."
+    [clean-images]="Removes the results of all image conversions generated by DAPS."
+    [clean-results]="Removes all generated documents and logfiles for a given DC- or MAIN-file.\nImage conversion results and profiled XML sources will not be deleted."
+    [clean]="Removes all profiled XML sources and temporary files generated by DAPS."
+    [color-pdf-name]="Print the file name that would result when building a color PDF."
+    [color-pdf]="Build a color PDF document from the XML sources."
+    [db2novdoc]="Converts DocBook4 XML sources to NovDoc (a subset of DocBook4)".
+    [debug]="DEBUGGING: Reserved for adding debug targets"
+    [desktop-files-dir-name]="Print the directory name that would result when building KDE desktop files."
+    [desktop-files]="Create desktop files for KDE."
+    [dist-all]="Creates tar archives with source graphics, source XML, and the resulting\nHTML build. Also builds a color PDF document."
+    [dist-book]="Creates a tar archive with the XML sources specified by rootid.\nNOTE: Graphics are not included and the unpacked sources may not validate.\n      To create tarballs containing images and a complete, valid set\n      of XML sources, use the command \"package-src\"."
+    [dist-desktop-files]="Create a tar archive with desktop files for KDE."
+    [dist-document-files-html]="Create a tar archive with document files for an HTML document referenced\nin the GNOME help system."
+    [dist-document-files-pdf]="Create document files for a PDF document referenced in the GNOME help system."
+    [dist-graphics-png]="Create a tar archive with all images from the set referenced\nin the DC- or the MAIN-file. All images will be converted to PNG."
+    [dist-graphics]="Create a tar archive with all images from the set referenced in the\nDC- or the MAIN-file. Images will be included in their \"native\"\nformat."
+    [dist-html-name]="Print the file name that would result when building a distributable tar archive\nof an HTML document."
+    [dist-html-single]="Print the file name that would result when building a distributable tar archive\nof a single file HTML document."
+    [dist-html]="Creates a distributable tar archive of an HTML document (including images)."
+    [dist-htmlsingle]="Creates a distributable tar archive of a single file HTML document\n(including images)."
+    [dist-jsp]="Creates a distributable tar archive of a JSP document (including images)."
+    [dist-xml]="Creates a tar archive with the XML sources specified by The MAIN file.\nNOTE: Graphics are not included and the unpacked sources may not validate.\n      To create tarballs containing images and a complete, valid set of\n      XML sources, use the command \"package-src\"."
+    [document-files-dir-name]="Print the directory name that would result when building\nGNOME document files."
+    [document-files-html]="Create document files for an HTML document referenced in the GNOME help system."
+    [document-files-pdf]="Create document files for a PDF document referenced in the GNOME help system."
+    [epub-name]="Print the file name that would result when building an eBook."
+    [epub]="Build an eBook from the XML sources."
+    [getimages]="List and/or display images (in a viewer of your choice) referenced in an\nXML file or by rootid."
+    [html-dir-name]="Print the directory name that would result when building an HTML book."
+    [html-single-name]="Print the file name that would result when building a single file HTML document."
+    [html-single]="Build a single file HTML document from the XML sources."
+    [html]="Build an HTML document from the XML sources."
+    [htmlsingle-name]="Print the file name that would result when building a single file HTML book."
+    [htmlsingle]="Build a single file HTML document from the XML sources."
+    [jana]="Validates ftp and http(s) links in XML sources."
+    [jsp-dir-name]="Print the file name that would result when building a JSP document."
+    [jsp]="Build a JSP document from the XML sources."
+    [locdrop]="Create all tar archives required to distribute a complete set for translation.\nRequires SVN hosting of the sources - files that need to be translated\nhave to be marked with the property doc:trans=yes."
+    [man]="Build one or more man pages from suitable XML sources. All <refentry> parts\nfrom the source file(s) will be transformed to man pages."
+    [missinggraphics]="Prints a list of images that are referenced in the XML sources but are missing\nin the images' source directory."
+    [nothing]="DEBUGGING: Benchmarking target."
+    [offspring]=""
+    [online-docs]="Creates a bigfile for the complete set and a tarball including all referenced\ngraphics in PNG format."
+    [online-localized]=""
+    [optipng]="Reduce the size of the source PNG images using \"optipng\".\nNOTE: This command will directly alter your source images!"
+    [package-html]="Create all archives and files needed for packaging an HTML document."
+    [package-jsp]="Create all archives and files needed for packaging a JSP document."
+    [package-pdf]="Create all archives and files needed for packaging a color PDF document."
+    [package-src-name]="Print the file name that would result when building a distributable source\narchive."
+    [package-src]="Creates a distributable source archive containg the sources of the complete set\nincluding the images."
+    [pdf-color-name]="Print the file name that would result when building a color PDF."
+    [pdf-color]="Build a color PDF document from the XML sources."
+    [pdf-name]="Print the file name that would result when building a grayscale PDF document."
+    [pdf]="Build a grayscale PDF document from the XML sources (with cropmarks if using\nthe XEP formatter)."
+    [penguin]=""
+    [prof]="Create profiled souces from the original XML sources. If the MAIN-file does\nnot contain profiling instructions, link the files into the profile directory."
+    [profile]="Create profiled souces from the original XML sources. If the MAIN-file does\nnot contain profiling instructions, link the files into the profile directory."
+    [profiledir]="Print the directory name that would result when profiling the XML sources."
+    [projectfiles]="Print a list of all XML source files used in the document referenced\nby the DC- or MAIN-file."
+    [projectgraphics]="Print a list of all source image used in the document referenced\nby the DC- or MAIN-file."
+    [provide-color-images]="Convert all image files used in the document referenced by the DC- or MAIN-file.\nAll files will be converted to PNG, \".dia\", \".eps\", and \".fig\" files\nwill also be converted into SVG and PDF. \".svg\" files  will also\nbe converted into PDF."
+    [provide-epub-images]="Prepare converted images for inclusion into an eBook."
+    [provide-images]="Convert all image files used in the document referenced by the DC- or MAIN-file\nto grayscale. All files will be converted to PNG, \".dia\", \".eps\", and\n\".fig\" files will also be converted into SVG and PDF. \".svg\" files  will\nalso be converted into PDF."
+    [real-clean]="Removes all data (documents, images, logfiles, profiled XML, ...) generated\nby DAPS"
+    [remainingfiles]="Print a list of all source XML files _not_ used in the document referenced\nby the DC- or MAIN-file."
+    [remaininggraphics]="Print a list of all source images _not_ used in the document referenced\nby the DC- or MAIN-file."
+    [showenv]="DEBUGGING: Target reserved for daps-docmanager"
+    [showvariable]="DEBUGGING: Show the value of a given variable.\nUsage: showvariable VARIABLE=<VARNAME>" 
+    [text]="Build an ASCII text document the from the XML sources."
+    [text-name]="Print the file name that would result when building an ASCII text document."
+    [txt]="Build am ASCII text document the from the XML sources."
+    [txt-name]="Print the file name that would result when building an ASCII text document."
+
+    [validate]="Validate the profiled XML sources referenced by the DC- or MAIN-file."
+    [warn-images]="Print a list of source images with non-unique names."
+    [webhelp]="Build an HTML document with a table of contents/search frame (aka webhelp)\nfrom the XML sources."
+    [webhelp-dir-name]="Print the directory name that would result when building a webhelp document."
+    [wiki]="Build a MediaWiki document from the XML sources. Images need to be uploaded\nmanually to the Wiki."
+    [wiki-name]="Print the file name that would result when building a MediaWiki document."
+    [xmlgraphics]="Print the list of generated images that will directly be used\nwhen building a document."
+    [xmlgraphics-bw]="Print the list of generated grayscale images that will directly be used\nwhen building a document."
+
 )
 
 
@@ -323,7 +425,7 @@ Global Options:
                             fallback. Useful if you have forks of your custom
                             stylesheets. The DocBook stylesheets will be used
                             as a last resort.
-                            Specify only the filename, not an absolute path.
+                            Specify only the file name, not an absolute path.
   --help, -h                Help
   --main, -m                Path to the main file defining your document.
                             Note: Options --main and --docconfig exclude
@@ -346,15 +448,12 @@ Subcommands:
 
   Generate Books:
     color-pdf, pdf-color      Color pdf book
-    dist                      b/w pdf with cropmarks for each chapter
     epub                      ePUB book
-    force                     b/w pdf with cropmarks. Force updating the
-                              profiled sources and the .fo file
     html                      HTML book
     html-single, htmlsingle   Single file HTML book
     jsp                       JSP book
     man                       man pages
-    pdf                       b/w pdf with cropmarks
+    pdf                       grayscale pdf (with cropmarks when using XEP)
     txt, text                 ASCII book
     webhelp                   HTML book with collapsable TOC and search
     wiki                      Single file MediaWiki book
@@ -373,7 +472,8 @@ Subcommands:
     dist-jsp                  JSP and graphics
     dist-xml                  Profiled XML sources of the whole set. Identical
                               to dist-book when using a book rather than a set.
-    locdrop                   Provide everything that is needed to translate a set
+    locdrop                   Provide everything that is needed to translate a
+                              set
 
   File lists:
     projectfiles              Print XML source files used by the book
@@ -384,8 +484,8 @@ Subcommands:
     warn-images                Print a list of non-unique image files
     xmlgraphics               Print (generated) color graphics really used to
                               generate the books
-    xmlgraphics-bw            Print (generated) b/w graphics really used to
-                              generate the books
+    xmlgraphics-bw            Print (generated) grayscale graphics really used
+                              to generate the books
 
   Cleaning up:
     clean                     Remove all profiled sources and temporary files
@@ -403,16 +503,9 @@ Subcommands:
                               (for KDE and GNOME)
     package-src               Provide profiled XML sources and graphics
 
-  Deploying (novell.com):
+  Deploying:
     online-docs               Provide a profiled XML bigfile and a graphics
                               tarball (PNG only)
-    online-localized          Provide a profiled XML bigfile and a graphics
-                              tarball (PNG only). All xrefs to other books from
-                              the set are replaced by ulinks pointing to
-                              <?provo dirname?>/id plus text like \"See book FOO,
-                              chapter BAR\" Useful for delivering translated
-                              manuals, when only part of the set has been
-                              translated
 
   Other Commands:
     chklink                   Linkchecker for links from <ulink> tags
@@ -425,7 +518,7 @@ Subcommands:
                               the XML sources if needed
 
   File and Directory Names:
-    <target>-name             Print resulting filename for <target>. <target>
+    <target>-name             Print resulting file name for <target>. <target>
                               may be one of color-pdf, epub, html-single,
                               pdf, txt
     <target>-dir-name         Print resulting directory name for <target>.
@@ -442,11 +535,20 @@ Type '$ME <subcommand> -h' for help on a specific subcommand.
 "
 }
 
+#    online-localized          Provide a profiled XML bigfile and a graphics
+#                              tarball (PNG only). All xrefs to other books from
+#                              the set are replaced by ulinks pointing to
+#                              <?provo dirname?>/id plus text like \"See book
+#                              FOO, chapter BAR\" Useful for delivering
+#                              translated manuals, when only part of the set
+#                              has been translated
+
+
 # ---------
 # Verbose error handling
 #
 function exit_on_error () {
-    echo "ERROR: ${1}" >&2
+    echo -e "ERROR: ${1}" >&2
     exit 1;
 }
 # ---------
