* BUGFIX: We now do an early! check whether a subcommand is correct or not           function run_subcmds has therefore been replaced by an           associative hash; the hash's key/value pairs can be eval'd to call           the function * BUGFIX: .fo files will always be regenerated (set to INTERMEDIATE). Thus the           user does not have to manually remove the .fo files in case the           fo-Stylesheets have been updated. * Enhancement (for jw): "daps -h <subcommand>" now shows help for subcommand
git-svn-id: svn+ssh://svn.code.sf.net/p/daps/svn/trunk/daps@396 2c1a2506-8097-4b87-b405-3e90b480097b

diff --git a/bin/daps b/bin/daps
--- a/bin/daps
+++ b/bin/daps
@@ -86,6 +86,107 @@ UNSETLIST=(
 unset "${VARLIST[@]}"
 unset "${UNSETLIST[@]}"
 
+#
+# Associative array with
+#  Key   = subcommand
+#  Value = function call (from lib/daps_functions)
+# 
+# The subcommands can be executed using eval:
+#   eval "${SUBCOMMANDS[$SUBCMD]} $SUBCMD ${SCMD_ARGS[@]}"
+# Using such an array rather than a function to call the subcommands has got
+# the advantage that we can very easily check whether a subcommand is valid
+# or not by just testing if ${SUBCOMMANDS[$SUBCMD]} is set
+
+declare -A SUBCOMMANDS
+SUBCOMMANDS=(
+    [all]=build_pdfs
+    [bigfile-reduced]=build_generic
+    [bigfile]=build_generic
+    [check]=call_make_nolog
+    [checklink]=checklink
+    [chklink]=checklink
+    [clean-all]=call_make_nolog
+    [clean-images]=call_make_nolog
+    [clean-results]=call_make_nolog
+    [clean]=call_make_nolog
+    [color-pdf-name]=show-names
+    [color-pdf]=build_pdfs
+    [db2novdoc]=build_generic
+    [desktop-files-dir-name]=show-names
+    [desktop-files]=build_generic
+    [dist-all]=profile_first
+    [dist-book]=build_generic
+    [dist-desktop-files]=build_generic
+    [dist-document-files-html]=build_generic
+    [dist-document-files-pdf]=build_generic
+    [dist-graphics-png]=build_generic
+    [dist-graphics]=build_generic
+    [dist-html-name]=show-names
+    [dist-html-single]=build_generic
+    [dist-html]=build_generic
+    [dist-htmlsingle]=build_generic
+    [dist-jsp]=build_generic
+    [dist-xml]=build_generic
+    [dist]=build_generic
+    [document-files-dir-name]=show-names
+    [document-files-html]=build_generic
+    [document-files-pdf]=build_generic
+    [epub-name]=show-names
+    [epub]=build_epub
+    [force]=build_pdfs
+    [getimages]=getimages
+    [html-dir-name]=show-names
+    [html-single-name]=show-names
+    [html-single]=build_html_jsp
+    [html]=build_html_jsp
+    [htmlsingle-name]=show-names
+    [htmlsingle]=build_html_jsp
+    [jana]=checklink
+    [jsp-dir-name]=show-names
+    [jsp]=build_html_jsp
+    [locdrop]=build_locdrop
+    [missinggraphics]=filelists
+    [nothing]=call_make_nolog
+    [offspring]=call_make_nolog
+    [online-docs]=build_generic
+    [online-localized]=build_generic
+    [optipng]=build_generic
+    [package-html]=packaging
+    [package-jsp]=packaging
+    [package-pdf]=packaging
+    [package-src-name]=show-names
+    [package-src]=packaging
+    [package]=packaging
+    [pdf-color-name]=show-names
+    [pdf-color]=build_pdfs
+    [pdf-name]=show-names
+    [pdf]=build_pdfs
+    [penguin]=call_make_nolog
+    [prof]=build_generic
+    [profile]=build_generic
+    [profiledir]=comments_remarks
+    [projectfiles]=filelists
+    [projectgraphics]=filelists
+    [provide-color-images]=build_generic
+    [provide-epub-images]=build_generic
+    [provide-images]=build_generic
+    [real-clean]=call_make_nolog
+    [remainingfiles]=filelists
+    [remaininggraphics]=filelists
+    [showenv]=show_env
+    [showvariable]=profile_first
+    [text]=build_generic
+    [txt-name]=show-names
+    [txt]=build_generic
+    [validate]=comments_remarks
+    [wiki-name]=show_names
+    [wiki]=build_generic
+    [xmlgraphics-bw]=filelists
+    [xmlgraphics]=filelists
+)
+
+
+
 # ----------------------------------------------------------------------------
 # FUNCTIONS
 #
@@ -290,78 +391,79 @@ function get_envfile () {
 # ---------
 # run the subcommands
 #
-function run_subcmd () {
-    case "$SUBCMD" in
-        all|color-pdf|force|pdf|pdf-color)
-	    build_pdfs $SUBCMD "${SCMD_ARGS[@]}"
-            exit
-	    ;;
-        checklink|chklink|jana)
-            checklink $SUBCMD "${SCMD_ARGS[@]}"
-            exit
-            ;;
-        epub)
-            build_epub $SUBCMD "${SCMD_ARGS[@]}"
-            exit
-            ;;
-        dist-all|showvariable)
-            # Always run "make profile" to generate an up-to-date profiled
-            # version
-            # Not doing so creates all kinds of hen-egg problems with filelists
-            # depending on $PROFILES, especially with the used images
-            profile_first $SUBCMD "${SCMD_ARGS[@]}"
-            exit
-            ;;
-        getimages)
-            getimages $SUBCMD "${SCMD_ARGS[@]}"
-            exit
-            ;;
-        html|htmlsingle|html-single|jsp)
-            build_html_jsp $SUBCMD "${SCMD_ARGS[@]}"
-            exit
-            ;;
-        locdrop)
-            build_locdrop $SUBCMD "${SCMD_ARGS[@]}"
-            exit
-            ;;
-        bigfile|bigfile-reduced|db2novdoc|desktop-files*|dist|dist-book|dist-desktop-files|dist-document-files*|dist-graphics|dist-graphics-png|dist-html|dist-htmlsingle|dist-html-single|dist-jsp|dist-xml|document-files-*|online-docs|online-localized|optipng|prof|profile|provide-color-images|provide-epub-images|provide-images|txt|text|wiki)
-            build_generic $SUBCMD "${SCMD_ARGS[@]}"
-            exit
-            ;;
-        package|package-html|package-pdf|package-jsp|package-src)
-            packaging $SUBCMD "${SCMD_ARGS[@]}"
-            exit
-            ;;
-        profiledir|validate)
-            comments_remarks $SUBCMD "${SCMD_ARGS[@]}"
-            exit
-            ;;
-        missinggraphics|projectfiles|projectgraphics|remainingfiles|remaininggraphics|xmlgraphics|xmlgraphics-bw)
-            filelists $SUBCMD "${SCMD_ARGS[@]}"
-            exit
-            ;;
-        check|clean|clean-all|clean-images|clean-results|nothing|offspring|package-src-name|penguin|real-clean)
-            # Writes no logfile
-            #
-            call_make_nolog $SUBCMD "${SCMD_ARGS[@]}"
-            exit
-            ;;
-        color-pdf-name|dist-html-name|epub-name|html-dir-name|htmlsingle-name|html-single-name|jsp-dir-name|pdf-color-name|pdf-name|txt-name|wiki-name)
-            # Writes no logfile
-            #
-            show_names $SUBCMD "${SCMD_ARGS[@]}"
-            exit
-            ;;        
-        showenv)
-            show_env
-            exit
-            ;;
-        *)
-            ccecho "error" "Error: Unknown command \"$SUBCMD\""
-            ccecho "normal" "Type '$ME help' to get a list of global parameters and commands"
-            exit 1;
-    esac
-}
+#function run_subcmd () {
+#    DRY_RUN=$1
+#    case "$SUBCMD" in
+#        all|color-pdf|force|pdf|pdf-color)
+#	    build_pdfs $SUBCMD "${SCMD_ARGS[@]}"
+#            exit
+#	    ;;
+#        checklink|chklink|jana)
+#            checklink $SUBCMD "${SCMD_ARGS[@]}"
+#            exit
+#            ;;
+#        epub)
+#            build_epub $SUBCMD "${SCMD_ARGS[@]}"
+#            exit
+#            ;;
+#        dist-all|showvariable)
+#            # Always run "make profile" to generate an up-to-date profiled
+#            # version
+#            # Not doing so creates all kinds of hen-egg problems with filelists
+#            # depending on $PROFILES, especially with the used images
+#            profile_first $SUBCMD "${SCMD_ARGS[@]}"
+#            exit
+#            ;;
+#        getimages)
+#            getimages $SUBCMD "${SCMD_ARGS[@]}"
+#            exit
+#            ;;
+#        html|htmlsingle|html-single|jsp)
+#            build_html_jsp $SUBCMD "${SCMD_ARGS[@]}"
+#            exit
+#            ;;
+#        locdrop)
+#            build_locdrop $SUBCMD "${SCMD_ARGS[@]}"
+#            exit
+#            ;;
+#        bigfile|bigfile-reduced|db2novdoc|desktop-files*|dist|dist-book|dist-desktop-files|dist-document-files*|dist-graphics|dist-graphics-png|dist-html|dist-htmlsingle|dist-html-single|dist-jsp|dist-xml|document-files-*|online-docs|online-localized|optipng|prof|profile|provide-color-images|provide-epub-images|provide-images|txt|text|wiki)
+#            build_generic $SUBCMD "${SCMD_ARGS[@]}"
+#            exit
+#            ;;
+#        package|package-html|package-pdf|package-jsp|package-src)
+#            packaging $SUBCMD "${SCMD_ARGS[@]}"
+#            exit
+#            ;;
+#        profiledir|validate)
+#            comments_remarks $SUBCMD "${SCMD_ARGS[@]}"
+#            exit
+#            ;;
+#        missinggraphics|projectfiles|projectgraphics|remainingfiles|remaininggraphics|xmlgraphics|xmlgraphics-bw)
+#            filelists $SUBCMD "${SCMD_ARGS[@]}"
+#            exit
+#            ;;
+#        check|clean|clean-all|clean-images|clean-results|nothing|offspring|package-src-name|penguin|real-clean)
+#            # Writes no logfile
+#            #
+#            call_make_nolog $SUBCMD "${SCMD_ARGS[@]}"
+#            exit
+#            ;;
+#        color-pdf-name|dist-html-name|epub-name|html-dir-name|htmlsingle-name|html-single-name|jsp-dir-name|pdf-color-name|pdf-name|txt-name|wiki-name)
+#            # Writes no logfile
+#            #
+#            show_names $SUBCMD "${SCMD_ARGS[@]}"
+#            exit
+#            ;;        
+#        showenv)
+#            show_env
+#            exit
+#            ;;
+#        *)
+#            ccecho "error" "Error: Unknown command \"$SUBCMD\""
+#            ccecho "normal" "Type '$ME help' to get a list of global parameters and commands"
+#            exit 1;
+#    esac
+#}
 
 
 # ----------------------------------------------------------------------------
@@ -472,8 +574,16 @@ while true ; do
 	    shift 2
             ;;
         -h|--help)
-            daps_help
-	    exit 0
+            # if it's just "-h/--help", then print the global daps help
+            # if "-h/--help" is followed by a subcommand, then set a marker
+            # to call the subcommand's help
+            shift;
+            if [[ "" = $2 ]]; then
+                daps_help
+                exit 0;
+            else
+                CALL_SCMDHELP=1
+            fi
             ;;
 	-v|--verbosity)
             # $VERBOSITY will be parsed in the makefiles
@@ -529,13 +639,24 @@ elif [[ help = $1 && -n $2 ]]; then
     #
     SUBCMD=$2
     declare -a SCMD_ARGS=( "-h" )
+elif [[ 1 = $CALL_SCMDHELP ]]; then
+    SUBCMD=$1
+    declare -a SCMD_ARGS=( "-h" )
 else
     # No help
     SUBCMD=$1
     shift
     declare -a SCMD_ARGS=( "$@" )
 fi
-    
+
+# Now that we have the subcommand, check whether it is valid
+
+if [[ -z ${SUBCOMMANDS[$SUBCMD]} ]]; then
+    ccecho "error" "Error: Unknown subcommand \"$SUBCMD\""
+    ccecho "normal" "Type '$ME help' to get a list of global parameters and subcommands"
+    exit 1;
+fi
+
 # Now check, whether subcommand help has been requested by -h or --help
 # anywhere in the argument string or if SCMD_ARGS contains bad strings
 #
@@ -632,7 +753,7 @@ esac
 # run help if requested
 #
 if [[ "${SCMD_ARGS[@]}" = "-h" ]]; then
-        run_subcmd
+    eval "${SUBCOMMANDS[$SUBCMD]} $SUBCMD ${SCMD_ARGS[@]}"
 fi
 
 
@@ -794,5 +915,7 @@ export "${VARLIST[@]}"
 # Finally, run the Subcommands
 #
 
-run_subcmd;
+eval "${SUBCOMMANDS[$SUBCMD]} $SUBCMD ${SCMD_ARGS[@]}"
+
+#run_subcmd;
 
