Help now exits with 0; error messages go to STDERR
git-svn-id: svn+ssh://svn.code.sf.net/p/daps/svn/trunk/daps@281 2c1a2506-8097-4b87-b405-3e90b480097b

diff --git a/docmanager/bin/dm b/docmanager/bin/dm
--- a/docmanager/bin/dm
+++ b/docmanager/bin/dm
@@ -17,7 +17,7 @@ DEBUG=0
 # Verbose error handling
 #
 function exit_on_error () {
-  echo "error" "ERROR: ${1}"
+  echo "error" "ERROR: ${1}" >&2
   exit 1;
 }
 
@@ -309,7 +309,7 @@ case "$SUBCMD" in
     help)
         # Output help text
         dm_help
-        exit 1
+        exit 0
         ;;
 
 # -------------------------------------------
