Bugfix: In case no rebuild was necessary, rsync deleted the previous results

diff --git a/autobuild/daps_autobuild.in b/autobuild/daps_autobuild.in
--- a/autobuild/daps_autobuild.in
+++ b/autobuild/daps_autobuild.in
@@ -50,7 +50,7 @@ Automatically build books defined in a config file and sync them to a server.
 The config file is an XML The config file is an XML file, see $ME --helpconfig forfile, see $ME --helpconfig for more information.
 
 Specifying config file with --config is mandatory, all other options are
-optional. 
+optional.
 
 Options:
 
@@ -95,7 +95,7 @@ Options:
 
   --validate
     Validate the config file specified with --config. Other options except
-    --schema will be ignored. 
+    --schema will be ignored.
 
 EOFhelptext
 }
@@ -131,11 +131,11 @@ section can only be occur once, while the set section can occur multiple times.
   <maintainer>E-Mail address for notifications. Optional.</maintainer>
   <vcs type="git|svn (mandatory)">
    <checkout>Checkout directory. Mandatory.</checkout>
-   <lastrev><!-- Leave empty, will be filled by script. Mandatory.--></latsrev> 
+   <lastrev><!-- Leave empty, will be filled by script. Mandatory.--></latsrev>
   </vcs>
  </set>
 EOFhelptext
-} 
+}
 
 function exit_on_error {
     # Print error message and exit with return code 1
@@ -160,12 +160,12 @@ function check_element {
     #  2. list (${array[@]})
     #
     local ELEMENT
- 
+
     [[ -z $1 ]] && exit_on_error "Function check_element must be called with an item to check for"
     [[ -z $2 ]] && exit_on_error "Function check_element must be called with an array"
 
-    for ELEMENT in "${@:2}"; do 
-	[[ "$ELEMENT" == "$1" ]] && return 0
+    for ELEMENT in "${@:2}"; do
+        [[ "$ELEMENT" == "$1" ]] && return 0
     done
     return 1
 }
@@ -204,13 +204,13 @@ function read_general {
     _DAPSROOT="$(read_config_value "$_START_XPATH" "dapsroot")"
     if [[ -n $_DAPSROOT ]]; then
         [[ -d $_DAPSROOT ]] || exit_on_error "DAPSROOT directory $_DAPSROOT does not exist"
-	CCECHO="$_DAPSROOT/bin/ccecho"
+        CCECHO="$_DAPSROOT/bin/ccecho"
     fi
 
-    if [[ 1 -eq $DO_RSYNC ]]; then 
-	_RSYNC_TARGET="$(read_config_value "${_START_XPATH}/rsync" "target")"
-	_RSYNC_FLAGS="$(read_config_value "${_START_XPATH}/rsync" "flags")"
-	[[ "$_RSYNC_FLAGS" =~ --delete ]] && $CCECHO "warn" "rsync flags contain --delete, manuals which fail to build will be deleted from server"
+    if [[ 1 -eq $DO_RSYNC ]]; then
+        _RSYNC_TARGET="$(read_config_value "${_START_XPATH}/rsync" "target")"
+        _RSYNC_FLAGS="$(read_config_value "${_START_XPATH}/rsync" "flags")"
+        [[ "$_RSYNC_FLAGS" =~ --delete ]] && $CCECHO "warn" "rsync flags contain --delete, manuals which fail to build will be deleted from server"
     fi
 }
 
@@ -232,8 +232,8 @@ function process_git {
     git pull -q || return 1
     echo "  * Updated git branch $GITBRANCH"
     if [[ 1 -eq $CHECK_VCS ]]; then
-	NEWREV="$(git rev-parse HEAD)" || return 2
-	[[ "$NEWREV" != "$_LASTREV" ]] && REBUILD="1"
+        NEWREV="$(git rev-parse HEAD)" || return 2
+        [[ "$NEWREV" != "$_LASTREV" ]] && REBUILD="1"
     fi
     return 0
 }
@@ -250,11 +250,11 @@ function process_svn {
     svn up -q >/dev/null || return 1
     echo "  * Updated svn working copy"
     if [[ 1 -eq $CHECK_VCS ]]; then
-	NEWREV="$(svnversion -c "$_CHECKOUT" . | sed -e 's/[MS]//g' -e 's/^[[:digit:]]*://')" || return 2
-	[[ "$NEWREV" != "$_LASTREV" ]] && REBUILD="1"
+        NEWREV="$(svnversion -c "$_CHECKOUT" . | sed -e 's/[MS]//g' -e 's/^[[:digit:]]*://')" || return 2
+        [[ "$NEWREV" != "$_LASTREV" ]] && REBUILD="1"
     fi
     return 0
-}	
+}
 
 
 function run_daps {
@@ -283,7 +283,7 @@ function run_daps {
     else
         SUBCMD="$_FORMAT"
     fi
-  
+
     NAME=${DCFILE//DC-/}
     BUILDDIR="${_BUILDDIR}/$_SET"
 
@@ -295,10 +295,10 @@ function run_daps {
     RUNDAPS="$DAPS_BASE_CMD"
     [[ 1 -eq $DEBUG ]] && RUNDAPS="$RUNDAPS --debug"
     RUNDAPS="$RUNDAPS $SUBCMD --name $NAME"
-    [[ -n $_DRAFT ]]        && RUNDAPS="$RUNDAPS --draft" 
+    [[ -n $_DRAFT ]]        && RUNDAPS="$RUNDAPS --draft"
     [[ -n $_REMARKS ]]      && RUNDAPS="$RUNDAPS --remarks"
     if [[ -n $_META ]]; then
-	[[ $SUBCMD = "html" || $SUBCMD = "pdf" ]] &&  RUNDAPS="$RUNDAPS --meta"
+        [[ $SUBCMD = "html" || $SUBCMD = "pdf" ]] &&  RUNDAPS="$RUNDAPS --meta"
     fi
 
     echo -n "  * Building $_FORMAT version of $DCFILE ... "
@@ -306,37 +306,37 @@ function run_daps {
     if [[ 0 -eq $? ]]; then
         $CCECHO "result" "Succeeded"
         SYNCDIR_DC="${SYNCDIR}/$NAME"
-	NAME_CMD_ARGS="--name $NAME"
+        NAME_CMD_ARGS="--name $NAME"
         mkdir -p "$SYNCDIR_DC"
-        [[ -n $_DRAFT ]]        && NAME_CMD_ARGS="$NAME_CMD_ARGS --draft" 
+        [[ -n $_DRAFT ]]        && NAME_CMD_ARGS="$NAME_CMD_ARGS --draft"
         [[ -n $_REMARKS ]]      && NAME_CMD_ARGS="$NAME_CMD_ARGS --remarks"
         if [[ -n $_META ]]; then
-	    [[ $SUBCMD = "html" || $SUBCMD = "pdf" ]] &&  NAME_CMD_ARGS="$NAME_CMD_ARGS --meta"
+            [[ $SUBCMD = "html" || $SUBCMD = "pdf" ]] &&  NAME_CMD_ARGS="$NAME_CMD_ARGS --meta"
         fi
-	NAME_CMD_ARGS="$NAME_CMD_ARGS 2>/dev/null"
+        NAME_CMD_ARGS="$NAME_CMD_ARGS 2>/dev/null"
         if [[ "pdf" = "$_FORMAT" ]]; then
-	    RESULT="$($DAPS_BASE_CMD pdf-name $NAME_CMD_ARGS)"
+            RESULT="$($DAPS_BASE_CMD pdf-name $NAME_CMD_ARGS)"
             mkdir -p "${SYNCDIR_DC}/$_FORMAT"
         elif [[ "html" = "$_FORMAT" ]]; then
-	    RESULT="$($DAPS_BASE_CMD html-dir-name $NAME_CMD_ARGS)"
-	elif [[ "single-html" = "$_FORMAT" ]]; then
-	    RESULT="$($DAPS_BASE_CMD html-dir-name --single $NAME_CMD_ARGS)"
+            RESULT="$($DAPS_BASE_CMD html-dir-name $NAME_CMD_ARGS)"
+        elif [[ "single-html" = "$_FORMAT" ]]; then
+            RESULT="$($DAPS_BASE_CMD html-dir-name --single $NAME_CMD_ARGS)"
         fi
             mv "$RESULT" "${SYNCDIR_DC}/$_FORMAT"
-	return 0
+        return 0
     else
         $CCECHO "warn" "Failed"
-	FAILURES=$((FAILURES + 1))
-	FAILED_BOOKS["$DC"]="${FAILED_BOOKS["$DC"]} $_FORMAT"
-    	ORIG_IFS="$IFS"
-	IFS=$'\n'
-	echo -e "\e[33m"
-    	for LINE in $RESULT; do
-	    echo -e "\t$LINE"
-	done
-	echo -e "\e[0m"
-	IFS="$ORIG_IFS"
-	return 1
+        FAILURES=$((FAILURES + 1))
+        FAILED_BOOKS["$DC"]="${FAILED_BOOKS["$DC"]} $_FORMAT"
+        ORIG_IFS="$IFS"
+        IFS=$'\n'
+        echo -e "\e[33m"
+        for LINE in $RESULT; do
+            echo -e "\t$LINE"
+        done
+        echo -e "\e[0m"
+        IFS="$ORIG_IFS"
+        return 1
     fi
 }
 
@@ -363,37 +363,37 @@ function failure_notification {
 
     _SET="$1"
     REASON="$2"
-    
+
     EMAIL="$(read_config_value "/daps-autobuild/set[@id='$SET']" "maintainer")"
 
     if [[ -n $EMAIL ]]; then
 
-	SUBJECT="[DAPS Auto]: Error report on $_SET ($REASON)"
+        SUBJECT="[DAPS Auto]: Error report on $_SET ($REASON)"
 
-	case $REASON in
-	    daps)
-		TEXT="While building manuals for set $_SET on ${FAILED_BOOKS["date"]}\nerrors occured on the following DC-files\n\n"
-		for KEY in "${!FAILED_BOOKS[@]}"; do
-		    [[ "date" == "$KEY" ]] && continue
-		    TEXT="$TEXT * $KEY:\t${FAILED_BOOKS["$KEY"]}\n"
-		done
-		;;
-	    git)
-		TEXT="Updating the git checkout for $_SET failed on ${FAILED_BOOKS["date"]}\n"
-		;;
-	    svn)
-		TEXT="Updating the SVN working copy for $_SET failed on ${FAILED_BOOKS["date"]}\n"
-		;;
-	esac
-	
-	TEXT="$TEXT\n-- \nYours friendly\n\tDAPS Auto reminder"
-	
-	echo -e "$TEXT" | mail -s "$SUBJECT" "$EMAIL" || return 2
+        case $REASON in
+            daps)
+                TEXT="While building manuals for set $_SET on ${FAILED_BOOKS["date"]}\nerrors occured on the following DC-files\n\n"
+                for KEY in "${!FAILED_BOOKS[@]}"; do
+                    [[ "date" == "$KEY" ]] && continue
+                    TEXT="$TEXT * $KEY:\t${FAILED_BOOKS["$KEY"]}\n"
+                done
+                ;;
+            git)
+                TEXT="Updating the git checkout for $_SET failed on ${FAILED_BOOKS["date"]}\n"
+                ;;
+            svn)
+                TEXT="Updating the SVN working copy for $_SET failed on ${FAILED_BOOKS["date"]}\n"
+                ;;
+        esac
+
+        TEXT="$TEXT\n-- \nYours friendly\n\tDAPS Auto reminder"
+
+        echo -e "$TEXT" | mail -s "$SUBJECT" "$EMAIL" || return 2
     fi
 
     return 0
 }
-    
+
 
 ################ MAIN ################
 
@@ -410,56 +410,56 @@ eval set -- "$ARGS"
 
 while true ; do
     case "$1" in
-	--config)
-	    [[ -f $2 ]] || exit_on_error "Not a valid path for --config"
-	    CONFIG="$(readlink -e "$2")"
-	    shift 2
-	    ;;
+        --config)
+            [[ -f $2 ]] || exit_on_error "Not a valid path for --config"
+            CONFIG="$(readlink -e "$2")"
+            shift 2
+            ;;
         --debug)
-	    DEBUG=1
-	    shift
-	    ;;
-	--force)
-	    CHECK_VCS=0
-	    shift
-	    ;;
-	-h|--help)
-	    usage
-	    exit 0
-	    ;;
-	--helpconfig)
-	    helpconfig
-	    exit 0
-	    ;;
-	--nosync)
-	    DO_RSYNC=0
-	    shift
-	    ;;
-	--notify)
-	    SEND_REPORTS=1
-	    shift
-	    ;;
-	--schema)
-	    SCHEMA="$2"
-	    shift 2
-	    ;;
-	--sections)
-	    SECTIONS="$2"
-	    shift 2
-	    ;;
-	--validate)
-	    validate
-	    if [[ 0 -ne $? ]]; then
-		exit_on_error "$CONFIG does not validate"
-	    else
-		echo "$CONFIG validates"
-		exit 0
-	    fi
-	    ;;
+            DEBUG=1
+            shift
+            ;;
+        --force)
+            CHECK_VCS=0
+            shift
+            ;;
+        -h|--help)
+            usage
+            exit 0
+            ;;
+        --helpconfig)
+            helpconfig
+            exit 0
+            ;;
+        --nosync)
+            DO_RSYNC=0
+            shift
+            ;;
+        --notify)
+            SEND_REPORTS=1
+            shift
+            ;;
+        --schema)
+            SCHEMA="$2"
+            shift 2
+            ;;
+        --sections)
+            SECTIONS="$2"
+            shift 2
+            ;;
+        --validate)
+            validate
+            if [[ 0 -ne $? ]]; then
+                exit_on_error "$CONFIG does not validate"
+            else
+                echo "$CONFIG validates"
+                exit 0
+            fi
+            ;;
         --) shift ; break ;;
         *) exit_on_error "Internal error while parsing the command line arguments!" ;;
     esac
-done	
+done
 
 # Check config/schema
 [[ -z $CONFIG ]] && exit_on_error "You must specify a config file with --config"
@@ -490,12 +490,12 @@ ALL_SETIDS=( $(xml sel -t -v "/daps-autobuild/set/@id" "$CONFIG") )
 read_general
 
 for SET in $SECTIONS; do
-    
+
     # check if SET is a valid section in the config file
     check_element "$SET" "${ALL_SETIDS[@]}"
     if [[ 1 -eq $? ]]; then
-	$CCECHO "warn" "$SET not configured in config file, skipping!"
-	continue
+        $CCECHO "warn" "$SET not configured in config file, skipping!"
+        continue
     fi
 
     _CHECKOUT=""
@@ -518,9 +518,9 @@ for SET in $SECTIONS; do
 
     # set rebuild to "1" if we do not check for revisions
     if [[ 1 -eq $CHECK_VCS ]]; then
-	REBUILD="0"
+        REBUILD="0"
     else
-	REBUILD="1"
+        REBUILD="1"
     fi
 
     # set up the sync directory
@@ -542,25 +542,25 @@ for SET in $SECTIONS; do
     _REMARKS="$(read_config_value "$START_XPATH" "@remarks")"
     _STYLEROOT="$(read_config_value "$START_XPATH" "styleroot")"
     _VCS="$(read_config_value "${START_XPATH}/vcs" "@type")"
-    
+
     # validity checks
     if [[ -n $_FB_STYLEROOT ]]; then
         if [[ ! -d $_STYLEROOT ]]; then
-	    $CCECHO "warn" "  FB_STYLEROOT directory '$_FB_STYLEROOT' does not exist,\n  using default"
-	   _FB_STYLEROOT="" 
-	fi
+            $CCECHO "warn" "  FB_STYLEROOT directory '$_FB_STYLEROOT' does not exist,\n  using default"
+           _FB_STYLEROOT=""
+        fi
     fi
 
     if [[ -n $_STYLEROOT ]]; then
         if [[ ! -d $_STYLEROOT ]]; then
-	    $CCECHO "warn" "  STYLEROOT directory '$_STYLEROOT' does not exist,\n  using default"
-	   _STYLEROOT="" 
-	fi
+            $CCECHO "warn" "  STYLEROOT directory '$_STYLEROOT' does not exist,\n  using default"
+           _STYLEROOT=""
+        fi
     fi
 
     if [[ ! -d $_CHECKOUT ]]; then
-	$CCECHO "warn" "  Checkout directory '$_CHECKOUT' does not exist!\n  Skipping $SET"
-	continue
+        $CCECHO "warn" "  Checkout directory '$_CHECKOUT' does not exist!\n  Skipping $SET"
+        continue
     fi
 
     pushd "$_CHECKOUT" >/dev/null
@@ -568,34 +568,34 @@ for SET in $SECTIONS; do
     #--------------------
     # update the checkout and check revisions
     if [[ $_VCS = "git" ]]; then
-	process_git
-	case $? in
-	    1)
-		$CCECHO "warn" "  Running 'git pull' in $_CHECKOUT failed!\n  Skipping $SET"
-		failure_notification "$SET" "git"
-		continue
-		;;
-	    2)
-		$CCECHO "warn" "  Wasn't able to get the current revision number from git"
-		;;
-	    3)
-		$CCECHO "warn" "  Running 'git co <branch>' in $_CHECKOUT failed!\n  Skipping $SET"
-		failure_notification "$SET" "git"
-		continue
-		;;
-	esac
+        process_git
+        case $? in
+            1)
+                $CCECHO "warn" "  Running 'git pull' in $_CHECKOUT failed!\n  Skipping $SET"
+                failure_notification "$SET" "git"
+                continue
+                ;;
+            2)
+                $CCECHO "warn" "  Wasn't able to get the current revision number from git"
+                ;;
+            3)
+                $CCECHO "warn" "  Running 'git co <branch>' in $_CHECKOUT failed!\n  Skipping $SET"
+                failure_notification "$SET" "git"
+                continue
+                ;;
+        esac
     elif [[ $_VCS = "svn" ]]; then
-	process_svn
-	case $? in
-	    1)
-		$CCECHO "warn" "  Running 'svn up' in $_CHECKOUT failed!\n  Skipping $SET"
-		failure_notification "$SET" "svn"
-		continue
-		;;
-	    2)
-		$CCECHO "warn" "  Wasn't able to get the current revision number from SVN"
-		;;
-	esac
+        process_svn
+        case $? in
+            1)
+                $CCECHO "warn" "  Running 'svn up' in $_CHECKOUT failed!\n  Skipping $SET"
+                failure_notification "$SET" "svn"
+                continue
+                ;;
+            2)
+                $CCECHO "warn" "  Wasn't able to get the current revision number from SVN"
+                ;;
+        esac
     fi
 
 
@@ -603,15 +603,15 @@ for SET in $SECTIONS; do
     # build the manuals
 
     if [[ 1 -eq $REBUILD ]]; then
-	for _FORMAT in $_FORMATS; do
+        for _FORMAT in $_FORMATS; do
             for DC in $_DCFILES; do
-		# Build!
-		run_daps "$_FORMAT" "$DC" "$SET"
+                # Build!
+                run_daps "$_FORMAT" "$DC" "$SET"
             done
-	done
+        done
     else
-	echo "  ==> Previous build still up-to-date, no rebuild needed"
-    fi     
+        echo "  ==> Previous build still up-to-date, no rebuild needed"
+    fi
 
     popd >/dev/null
 
@@ -620,39 +620,39 @@ for SET in $SECTIONS; do
     # check for build failures
 
     if [[ 0 -ne $FAILURES ]]; then
-	$CCECHO "warn" "  ==> Counted $FAILURES build failure(s)"
-	# if there are build failures, do not run rsync with --delete
-	RSYNC_DELETE=""
-	# send an error report
-	if [[ 1 -eq $SEND_REPORTS ]]; then
-	    failure_notification "$SET" "daps"
-	    case $? in
-		1)
-		    $CCECHO "warn" "Could not send error report (Postfix not running)"
-		    ;;
-		2)
-		    $CCECHO "warn" "Could not send error report (mail command failed)"
-		    ;;
-	    esac
-	fi
+        $CCECHO "warn" "  ==> Counted $FAILURES build failure(s)"
+        # if there are build failures, do not run rsync with --delete
+        RSYNC_DELETE=""
+        # send an error report
+        if [[ 1 -eq $SEND_REPORTS ]]; then
+            failure_notification "$SET" "daps"
+            case $? in
+                1)
+                    $CCECHO "warn" "Could not send error report (Postfix not running)"
+                    ;;
+                2)
+                    $CCECHO "warn" "Could not send error report (mail command failed)"
+                    ;;
+            esac
+        fi
     else
-	# No build failures; set new revision to config
-	xml ed -P -L -u "/daps-autobuild/set[@id='$SET']/vcs/lastrev" -v "$NEWREV" "$CONFIG"
-	RSYNC_DELETE="--delete"
+        # No build failures; set new revision to config
+        xml ed -P -L -u "/daps-autobuild/set[@id='$SET']/vcs/lastrev" -v "$NEWREV" "$CONFIG"
+        RSYNC_DELETE="--delete"
     fi
 
     #--------------------
     # rsync
 
-    if [[ 1 -eq $DO_RSYNC ]]; then
-	$RSYNC $_RSYNC_FLAGS $RSYNC_DELETE $SYNCDIR $_RSYNC_TARGET
-	if [[ 0 -eq $? ]]; then
-	    $CCECHO "result" "  Rsync successful"
-	else
-	    $CCECHO "warn" "  Rsync failed"
-	fi
+    if [[ 1 -eq $DO_RSYNC && 1 -eq $REBUILD ]]; then
+        $RSYNC $_RSYNC_FLAGS $RSYNC_DELETE $SYNCDIR $_RSYNC_TARGET
+        if [[ 0 -eq $? ]]; then
+            $CCECHO "result" "  Rsync successful"
+        else
+            $CCECHO "warn" "  Rsync failed"
+        fi
     else
-	$CCECHO "info" "  Skipping rsync"
+        $CCECHO "info" "  Skipping rsync"
     fi
 
     echo
