Fixes #369 Code review: Check Variable Assignments

diff --git a/lib/daps_functions b/lib/daps_functions
--- a/lib/daps_functions
+++ b/lib/daps_functions
@@ -357,7 +357,7 @@ function init_env {
 
     # There should only be one DC-file in $R_DIR
     #
-    DC_COUNT=$(find -L "$R_DIR" -maxdepth 1 -name "${CONF_PREFIX}*" -type f | wc -l)
+    DC_COUNT=$(find -L "$R_DIR" -maxdepth 1 -name "${CONF_PREFIX}*" -type f | wc -l 2>/dev/null)
     if [[ $DC_COUNT -gt 1 && 0 != "$VERBOSITY" ]]; then
         ccecho "warn" "$R_DIR contains more than one DC-file"
     fi
@@ -1551,12 +1551,12 @@ function unpack-locdrop {
     for TAR in $P_TRANS_FILES; do
     if [[ -f $TAR ]]; then
         pushd "$P_OUTPUT_DIR" > /dev/null
-        MANIFEST_TRANS=$(tar tfj "$TAR" | grep "$MFT_TRANS_SUFF")
+        MANIFEST_TRANS=$(tar tfj "$TAR" | grep "$MFT_TRANS_SUFF" 2>/dev/null) || exit_on_error "Could not get manifest of translated files"
         ALL_MANIFEST_TRANS_FILES=( "${ALL_MANIFEST_TRANS_FILES[@]}" "$MANIFEST_TRANS" )
-        MANIFEST_NOTRANS=$(tar tfj "$TAR" | grep "$MFT_NOTRANS_SUFF")
+        MANIFEST_NOTRANS=$(tar tfj "$TAR" | grep "$MFT_NOTRANS_SUFF" 2>/dev/null) || exit_on_error "Could not get manifest of non-translated files"
         ALL_MANIFEST_NOTRANS_FILES=( "${ALL_MANIFEST_NOTRANS_FILES[@]}" "$MANIFEST_NOTRANS" )
-        tar xfj "$TAR" "$MANIFEST_TRANS" "$MANIFEST_NOTRANS"
-        tar xfj "$TAR" $(cat "$MANIFEST_TRANS")
+        tar xfj "$TAR" "$MANIFEST_TRANS" "$MANIFEST_NOTRANS" 2>/dev/null || exit_on_error "Could not extract manifest files from tarball"
+        tar xfj "$TAR" $(cat "$MANIFEST_TRANS") 2>/dev/null || exit_on_error "Could not extract manifest files from tarball"
         popd >/dev/null
     else
         exit_on_error "Fatal: $TAR does not exist"
@@ -1600,14 +1600,14 @@ function unpack-locdrop {
 
     # get all files unique to the notrans lists (the ones that have not
     # been translated)
-    LINK_NOTRANS_FILES=$(comm -1 -3 <(echo -e "$ALL_TRANS_FILES") <(echo -e "$ALL_NOTRANS_FILES"))
+    LINK_NOTRANS_FILES=$(comm -1 -3 <(echo -e "$ALL_TRANS_FILES") <(echo -e "$ALL_NOTRANS_FILES") 2>/dev/null) || exit_on_error "Could not get list of files that have not been translated"
 
     # Process LINK_NOTRANS_FILES to get the file lists we need
     #  the awk statements matches multiple occurrences on a single line
     #
-    DCFILE_LIST=$(awk '{for(i=1;i<=NF;++i)if($i~/DC-[^ ]*/)print $i}' <(echo "$LINK_NOTRANS_FILES"))
-    NO_DCFILE_LIST=$(awk '{for(i=1;i<=NF;++i)if($i !~ /DC-[^ ]*/)print $i}' <(echo "$LINK_NOTRANS_FILES"))
-    XML_FILE_LIST=$(awk -v path="${P_NOTRANS_DIR}/" '{for(i=1;i<=NF;++i)if($i~/xml\/.*\.xml/)print path $i}' <(echo "$LINK_NOTRANS_FILES"))
+    DCFILE_LIST=$(awk '{for(i=1;i<=NF;++i)if($i~/DC-[^ ]*/)print $i}' <(echo "$LINK_NOTRANS_FILES") 2>/dev/null) || exit_on_error "Could not get list of DC files"
+    NO_DCFILE_LIST=$(awk '{for(i=1;i<=NF;++i)if($i !~ /DC-[^ ]*/)print $i}' <(echo "$LINK_NOTRANS_FILES") 2>/dev/null) || exit_on_error "Could not get list of images that have not been 'translated'"
+    XML_FILE_LIST=$(awk -v path="${P_NOTRANS_DIR}/" '{for(i=1;i<=NF;++i)if($i~/xml\/.*\.xml/)print path $i}' <(echo "$LINK_NOTRANS_FILES") 2>/dev/null) || exit_on_error "Could not get list of files that have been translated"
 
     # Copy remaining DC-files
     #
@@ -1986,7 +1986,7 @@ function getimages {
 
     if [[ -n $P_FILE ]]; then
         if [[ -f $P_FILE ]]; then
-            ROOTID=$($XSLTPROC --stylesheet "$DAPSROOT/daps-xslt/common/get-rootelement-id.xsl" --file "$P_FILE" "$XSLTPROCESSOR") || exit_on_error "Cannot get a rootid from file $FILE"
+            ROOTID=$($XSLTPROC --stylesheet "$DAPSROOT/daps-xslt/common/get-rootelement-id.xsl" --file "$P_FILE" "$XSLTPROCESSOR" 2>/dev/null) || exit_on_error "Cannot get a rootid from file $FILE"
             export ROOTID
         else
             exit_on_error "File $P_FILE does not exist"
@@ -2024,7 +2024,7 @@ function getimages {
         else
             for IMAGE in "${IMGLIST[@]}"; do
                 if [[ $MOD ]]; then
-                MODIFIED=$(stat -c %y "$IMAGE" | cut -d '.' -f1)
+                MODIFIED=$(stat -c %y "$IMAGE" | cut -d '.' -f1 2>/dev/null)
                 echo "${IMAGE} (${MODIFIED})"
                 else
                 echo "${IMAGE}"
@@ -2133,7 +2133,7 @@ function spellcheck {
     for FILE in "${FILELIST[@]}"; do
         test -f "$FILE" || ccecho "warn" "File $FILE does not exist"
         if [[ 1 = "$LISTMODE" ]]; then
-            LISTOUTPUT=$($SPELLCMD list < "$FILE" | sort -u)
+            LISTOUTPUT=$($SPELLCMD list < "$FILE" | sort -u 2>/dev/null)
             [[ -n "$LISTOUTPUT" ]] && echo -e "$FILE\n------------------------------\n$LISTOUTPUT\n"
             LISTOUTPUT=""
         else
@@ -2188,7 +2188,7 @@ function stylecheck {
 
     if [[ -n "$P_FILE" ]]; then
         if [[ -f $P_FILE ]]; then
-            ROOTID=$($XSLTPROC --stylesheet "$DAPSROOT/daps-xslt/common/get-rootelement-id.xsl" --file "$P_FILE" "$XSLTPROCESSOR") || exit_on_error "Cannot get a rootid from file $FILE"
+            ROOTID=$($XSLTPROC --stylesheet "$DAPSROOT/daps-xslt/common/get-rootelement-id.xsl" --file "$P_FILE" "$XSLTPROCESSOR" 2>/dev/null) || exit_on_error "Cannot get a rootid from file $FILE"
         export ROOTID
         else
             exit_on_error "File $P_FILE does not exist"
@@ -2384,7 +2384,7 @@ function no_opts {
         # Use the cd commands to avoid errors when running DAPS from
         # one of the directories that get removed
         #
-        CURR_DIR=$(pwd)
+        CURR_DIR=$(pwd 2>/dev/null)
         cd $DOC_DIR > /dev/null
         call_make "$SUB_CMD" "$@"
         [[ -d $CURR_DIR ]] && cd $CURR_DIR
