Added a new subcommend: init, which creates a working environment incl. an ENV file and a xml/MAIN
git-svn-id: svn+ssh://svn.code.sf.net/p/daps/svn/trunk/daps@156 2c1a2506-8097-4b87-b405-3e90b480097b

diff --git a/lib/daps_functions b/lib/daps_functions
--- a/lib/daps_functions
+++ b/lib/daps_functions
@@ -26,6 +26,25 @@
 # ---------
 # Calling make and writing a log file 
 #
+
+function setup_builddir {
+    # Create the log directory and a link to the ENV-file in R_DIR
+    # (R_DIR and LOG_DIR are set in bin/daps) 
+
+    mkdir -p $LOG_DIR || exit_on_error "Cannot create $LOG_DIR"
+
+    if [[ ! -f ${R_DIR}/$ENVFILE ]]; then
+        ln -sf ${BASE_DIR}/$ENVFILE ${R_DIR}/$ENVFILE || ccecho "warn" "Warning: Cannot create link to $ENVFILE in $R_DIR"
+    fi
+
+    # There should only be one ENVFILE in $R_DIR
+    #
+    ENV_COUNT=$(find -L $R_DIR -maxdepth 1 -name "${CONF_PREFIX}*" -type f | wc -l)
+    if [[ $ENV_COUNT -gt 1 ]]; then
+        ccecho "warn" "$R_DIR contains more than one ENVFILE"
+    fi
+}
+    
 function call_make () {
     local TARGET LOGFILE MCMD
 
@@ -35,6 +54,8 @@ function call_make () {
     #
     TARGET=$1
     shift
+
+    setup_builddir
     
     MCMD="$MAKECMD -f $DTDROOT/make/common.mk $TARGET $@"
     
@@ -75,6 +96,9 @@ function call_make_nolog () {
     # is not necessary (e.g. for targets clean*)
     local TARGET MCMD
     TARGET=$1
+
+    setup_builddir
+    
     MCMD="$MAKECMD -f $DTDROOT/make/common.mk $TARGET $@"
     if [[ 1 = $PRETTY_FILELIST ]]; then
         eval "$MCMD 2>/dev/null" | sed 's/ /\n/g' | sort
@@ -87,6 +111,82 @@ function wrong_parameter () {
     local TARGET PARAM
     TARGET=$1
     echo "Type '$ME $TARGET help' to get a list of valid parameters"
+    exit 1;
+}
+
+function init_wd () {
+    # Initialize a working directory to get started with daps
+    #
+
+    test -z "$BASE_DIR" && exit_on_error "You must specify BASE_DIR when calling $ME init"
+    
+    SARGS=$(getopt -o h -l help,name:,rootelement: -n $0 -- "${SCMD_ARGS[@]}")
+    if [[ 1 = $? ]]; then
+        wrong_parameter "$TARGET"
+    fi
+    eval set -- "$SARGS"
+    while true ; do
+	case "$1" in
+            -h|--help)
+                help_scmd_head "Create a working environment for a book/article"
+                help_dirname
+                help_rootelement
+                echo
+		exit 0
+		;;
+            --dirname)
+                DIR_NAME="$2"
+                shift 2
+                ;;
+	    --rootelement)
+                if [[ article = $2 || book = $2 ]]; then
+                    ROOTELEMENT="$2"
+                else
+                    exit_on_error "ROOTELEMENT must be either article or book"
+                fi
+		shift 2
+		;;
+            --) shift ; break ;;
+            *) wrong_parameter "$TARGET $1" ;;
+	esac
+    done
+
+    # default when not set is book
+    test -z $ROOTELEMENT && ROOTELEMENT=book
+    
+    if [[ -n $PDFNAME ]]; then
+        BOOK="$PDFNAME"
+    else
+        BOOK="${ENVFILE#*${CONF_PREFIX}}"
+    fi
+    
+    if [[ -z $DIR_NAME ]]; then
+        DIR_NAME=$BOOK
+    fi
+    
+    BASE_DIR="${BASE_DIR}/$BOOK"
+    R_DIR="${BASE_DIR}/build/${BOOK}"
+    LOG_DIR="${R_DIR}/log"
+    
+    # Create BASE_DIR and needed subdirectories
+    mkdir -p $BASE_DIR
+    mkdir -p ${BASE_DIR}/images/src/{dia,fig,png,svg} ${BASE_DIR}/xml
+
+    # copy the templates
+    #
+    # ENV file
+    cp ${LIB_DIR}/templates/ENV-file.template ${BASE_DIR}/$ENVFILE && \
+        sed -i s/§§MAIN§§/MAIN-$BOOK.xml/g ${BASE_DIR}/$ENVFILE
+    # MAIN
+    cp ${LIB_DIR}/templates/MAIN.$ROOTELEMENT.template ${BASE_DIR}/xml/MAIN-${BOOK}.xml
+    # graphics
+    cp ${LIB_DIR}/templates/example{1,2}.png ${BASE_DIR}/images/src/png/
+  
+    setup_builddir
+    if [[ 1 = $VERBOSE ]]; then
+        ccecho "result" "Successfully created a working environment at"
+    fi
+    ccecho "result" "${BASE_DIR}"
     exit 1;
 }
 
@@ -117,7 +217,7 @@ function build_pdfs () {
 		shift
 		;;
 	    --fop)
-                if [[ $2 = xep || $2 = fop ]]; then
+                if [[ xep = $2 || fop = $2 ]]; then
                     export FOPTYPE="$2"
                     export FOP="${LIB_DIR}/daps-$2"
                 else
@@ -458,6 +558,9 @@ function packaging () {
     
 }
 
+ 
+
+
 # ----------------------------------------------------------------------------
 # Help functions
 #
@@ -477,6 +580,11 @@ $1
 function help_comments () {
     echo "        --comments, -c            Include XML comments in profiled sources
                                   Default: off"  
+}
+function help_dirname () {
+    echo "    --dirname=DIR                 Directory names to be created in BASE_DIR
+                              Default: generated by stripping 'ENV-' from the
+                              ENV filename"
 }
 function help_draft () {
     echo "    --draft, -d               Add a 'DRAFT' watermark to all pages of the book
@@ -520,6 +628,11 @@ function help_pretty () {
 function help_remarks () {
     echo "    --remarks, -r             Include remarks (<remark>...</remark>) in book
                               Default: off"  
+}
+function help_rootelement () {
+    echo "    --rootelement=ELEMENT     Specify a ROOTELEMENT for your main DocBook XML file
+                              must be one either article or book.
+                              Default: book"
 }
 function help_rootid () {
     echo "    --rootid=ID               Specify a ROOTID to build only parts of a book
