Code cleanup: Use proper syntax for integer tests
Use "-eq"/"-ne" rather than "="/"!="

diff --git a/lib/getimages b/lib/getimages
--- a/lib/getimages
+++ b/lib/getimages
@@ -21,7 +21,7 @@
 ###########################################################################
 function getimages {
     local SHORT_OPTS LONG_OPTS SUB_CMD
-    local COMPACT FILE SHOW
+    local COMPACT FILE SHOW IVIEWER
     local -a IMGLIST
 
     SUB_CMD=$1
@@ -39,7 +39,7 @@ function getimages {
     eval set -- "$P_REMAIN_ARGS"
 
     #------ Computing the values returned from the parser -----
-    if [[ 1 = "$P_HELP" ]]; then
+    if [[ 1 -eq $P_HELP ]]; then
         help_scmd_head "$SUB_CMD" "${HELP_SUBCOMMAND[$SUB_CMD]}"
         help_compact
         help_file
@@ -53,7 +53,7 @@ function getimages {
 
     # set ROOTID - either directly or via $FILE
     if [[ -z "$P_ROOTID" && -z "$P_FILE" ]]; then
-        if [[ 0 != $VERBOSITY ]]; then
+        if [[ 0 -ne $VERBOSITY ]]; then
             ccecho "info" "Neither file nor rootid specified, using rootid from DC-file"
         fi
     elif [[ -n "$P_ROOTID" && -n "$P_FILE" ]]; then
@@ -66,14 +66,14 @@ function getimages {
     fi
 
     # IMG_VIEWER may also be set via config file:
-    if [[ $SHOW ]]; then
+    if [[ 1 -eq $SHOW ]]; then
         if [[ -z "$IMG_VIEWER" ]]; then
             exit_on_error "Please specify an image viewer via command-line (--viewer) or via config file"
         else
-            IMG_VIEWER=$(which "$IMG_VIEWER" 2>/dev/null)
-            if [[ 0 -lt $? ]]; then # which command failed
+            IVIEWER=$(which "$IMG_VIEWER" 2>/dev/null)
+            if [[ 0 -ne $? ]]; then # which command failed
                 # Viewer not installed
-                exit_on_error "Cannot find VIEWER $IMG_VIEWER. Please check your coimmand line or config file"
+                exit_on_error "Cannot find VIEWER command ($IMG_VIEWER). Is it installed?"
             fi
         fi
     fi
@@ -81,7 +81,7 @@ function getimages {
     # get the image list
     # we can use projectgraphics, since it returns images for a given rootid
     IMGLIST=( $(call_make list-srcfiles silent LIST_NODC=1 LIST_NOENT=1 LIST_NOXML=1) )
-    if [[ 0 != $? ]]; then
+    if [[ 0 -ne $? ]]; then
         exit_on_error "Failed to get list of images"
     fi
 
@@ -90,14 +90,14 @@ function getimages {
             echo -e "${IMGLIST[*]}\n"
         else
             for IMAGE in "${IMGLIST[@]}"; do
-                if [[ 1 = "$MOD" ]]; then
+                if [[ 1 -eq $MOD ]]; then
                     MODIFIED=$(stat -c %y "$IMAGE" | cut -d '.' -f1 2>/dev/null)
                     echo "${IMAGE} (${MODIFIED})"
                 else
                     echo "${IMAGE}"
                 fi
             done  | column -t
-            if [[ $SHOW ]]; then
+            if [[ 1 -eq $SHOW ]]; then
                 $IMG_VIEWER "${IMGLIST[@]}" &
             fi
         fi
