Fix #533: Remove dm:docmanager block for locdrops
New option 'daps unpack-locdrop --remove-dm' now removes <dm:docmanager>
blocks from translated files (non-translated files remain untouched)

diff --git a/lib/unpack-locdrop b/lib/unpack-locdrop
--- a/lib/unpack-locdrop
+++ b/lib/unpack-locdrop
@@ -34,7 +34,7 @@ function unpack-locdrop {
     shift
 
     SHORT_OPTS="h"
-    LONG_OPTS="help,notrans-dir:,optipng,output-dir:,trans-files:"
+    LONG_OPTS="help,notrans-dir:,optipng,output-dir:,remove-dm,trans-files:"
 
     parse_args "$SHORT_OPTS" "$LONG_OPTS" "$SUB_CMD" "$@"
     eval set -- "$P_REMAIN_ARGS"
@@ -47,6 +47,7 @@ function unpack-locdrop {
         help_notrans-dir
         help_optipng
         help_output-dir
+        help_remove-dm
         echo
         exit 0
     fi
@@ -144,11 +145,11 @@ function unpack-locdrop {
     # the awk statements matches multiple occurrences on a single line
     #
     DCFILE_LIST=$(awk '{for(i=1;i<=NF;++i)if($i~/DC-[^ ]*/)print $i}' <(echo "$LINK_NOTRANS_FILES") 2>/dev/null) || exit_on_error "Could not get list of DC files"
-    NO_DCFILE_LIST=$(awk '{for(i=1;i<=NF;++i)if($i !~ /DC-[^ ]*/)print $i}' <(echo "$LINK_NOTRANS_FILES") 2>/dev/null) || exit_on_error "Could not get list of images that have not been 'translated'"
+    NO_DCFILE_LIST=$(awk '{for(i=1;i<=NF;++i)if($i !~ /DC-[^ ]*/)print $i}' <(echo "$LINK_NOTRANS_FILES") 2>/dev/null) || exit_on_error "Could not get list of images and XML files that have not been 'translated'"
 
     # Get a list of all xml files, we need to query them for entities
     #
-    XML_FILE_LIST=$(awk -v path="${P_NOTRANS_DIR}/" '{for(i=1;i<=NF;++i)if($i~/xml\/.*\.xml/)print path $i}' <(echo "$ALL_TRANS_FILES $ALL_NOTRANS_FILES") 2>/dev/null) || exit_on_error "Could not get list of files that have been translated"
+    XML_FILE_LIST=$(awk -v path="${P_NOTRANS_DIR}/" '{for(i=1;i<=NF;++i)if($i~/xml\/.*\.xml/)print path $i}' <(echo "$ALL_TRANS_FILES $ALL_NOTRANS_FILES") 2>/dev/null) || exit_on_error "Could not get list of all XML files"
 
     # Copy remaining DC-files
     #
@@ -162,9 +163,35 @@ function unpack-locdrop {
         fi
     done
 
+    # Remove the <dm:docmanager> part from the XML files, we cannot read
+    # Chinese bug reports and therefore do not want to encourage users
+    # to send them
+    #
+
+    if [[ 1  = "$P_REMOVEDM" ]]; then
+
+        echo "Removing <dm:docmanager> blocks"
+
+        # check for xmlstarlet binary
+        for _binary in xmlstarlet xml; do
+            XMLSTARLET=$(which $_binary 2>/dev/null)
+            [[ 0 -eq $? ]] && break
+        done
+        [[ -z $XMLSTARLET ]] && exit_on_error "Required package \"xmlstarlet\" is not installed"
+
+        #
+        # Get a list of all translated xml files
+        #
+        XML_TRANS_FILE_LIST=$(awk '{for(i=1;i<=NF;++i)if($i~/xml\/.*\.xml/)print $i}' <(echo "$ALL_TRANS_FILES") 2>/dev/null) || exit_on_error "Could not get list of translated XML files"
+        for _XML_TRANS_FILE in $XML_TRANS_FILE_LIST; do
+            #echo "$_XML_TRANS_FILE"
+            $XMLSTARLET ed -S --inplace -N dm="urn:x-suse:ns:docmanager" -d "//dm:docmanager" $_XML_TRANS_FILE
+        done
+    fi
+
     # Link not translated images and XML files
     #
-    echo "Linking images"
+    echo "Linking xml files and images"
     for DATA in $NO_DCFILE_LIST; do
     if [[ -f ${P_NOTRANS_DIR}/$DATA ]]; then
         DIR="$(dirname "$DATA")"
@@ -224,6 +251,13 @@ function help_notrans-dir {
                               Optional. If not specified, the dirname of the
                               DC-file is used.
                               Default: DC-file directory
+EOF
+}
+function help_remove-dm {
+    cat <<EOF
+    --remove-dm               When used, an existing <dm:docmanager> block
+                              will be removed from the translated files.
+                              Default: unset
 EOF
 }
 function help_trans-files {
