Merged in kpetsch's support for pipes for xsltproc; added pipe support for saxon (via tmp-file, since saxon does not support getiing a file from STDIN
git-svn-id: svn+ssh://svn.code.sf.net/p/daps/svn/trunk/daps@2696 2c1a2506-8097-4b87-b405-3e90b480097b

diff --git a/libexec/daps-xslt b/libexec/daps-xslt
--- a/libexec/daps-xslt
+++ b/libexec/daps-xslt
@@ -32,7 +32,7 @@ declare -a PARMS
 # final list of stringparams/params
 declare -a PARAMETERS
 
-unset DEBUG STRPARMS PARMS CATALOG
+unset DEBUG STRPARMS PARMS CATALOG XMLFULL
 
 # setting catalog for the resolver
 #
@@ -215,7 +215,20 @@ process_params () {
     echo "$RESULT"
 }
 
-
+# function to check if input is coming from a pipe
+piped_input () {
+    if [[ -p /dev/fd/0 ]]; then
+	while read data; do
+	    XMLFULL="$XMLFULL$data "
+        done
+        if [[ $PROCESSOR =~ saxon ]]; then
+            # saxon does not support getting input from STDIN ;-((
+            XML_TMP_FILE=$(mktemp -q --tmpdir daps_saxon.XXXXXXXX) || exit_on_error "Could not create a temporary file for saxon"
+            echo "$XMLFULL" >> $XML_TMP_FILE
+            XMLFILE=$XML_TMP_FILE
+        fi
+    fi
+}
 
 #----------------------------------------------------------------------------
 # MAIN
@@ -225,6 +238,7 @@ process_params () {
 export POSIXLY_CORRECT=1
 
 ARGS=$(getopt -o "hxno:vs:f:" -l "help,xinclude,param:,stringparam:,nonet,output:,novalid,stylesheet:,file:,debug,catalog:" -n "$ME" -- "$@")
+
 eval set -- "$ARGS"
 
 while true; do
@@ -274,13 +288,19 @@ while true; do
             # allow multiple calls of this parameter; if saxon, then use ";" as
             # separator, if xsltproc use " " and export XML_CATALOG_FILES
 	    CATALOG="$CATALOG $2;"
-	    shift 2;;	
+	    shift 2;;
+#	--input)
+	    
 	--)
 	    shift
 	    break;;
         *) exit_on_error "Internal error!" ;;
     esac
 done
+# -input param
+# -check input+param together
+# -aufruf für xsltproc bei input zu ändern (mit echo)
+# -
 
 unset POSIXLY_CORRECT
 
@@ -296,11 +316,17 @@ else
 fi
 PROCESSOR_ARGS="$@"
 
+#----
+# Get input from pipe (in case a pipe exists)
+#
+piped_input
+
+
 #-----
 # Check if all mandatory options are set
 #
 [[ -z $STYLESHEET ]] && exit_on_error "you must specify a stylesheet with --stylesheet <STYLESHEET>"
-[[ -z $XMLFILE ]] && exit_on_error "you must specify an XML file with --file"
+[[ -z $XMLFILE && -t 0 ]] && exit_on_error "you must either specify an XML file with --file or pipe it into $ME"
 
 #-----
 # run the XSLT processor
@@ -315,21 +341,40 @@ if [[ $PROCESSOR =~ xsltproc ]]; then
     fi
     
     COMMAND="$XSLTPROC $PROCESSOR_ARGS $XINCLUDE ${PARAMETERS[@]} $OUTPUT $STYLESHEET $XMLFILE"
+    
     if [[ -n $DEBUG ]]; then
         echo "---------------------------------------------------------"
-        echo -e "Running the following command:\n$COMMAND"
+        echo "Running the following command:"
+        if [[ -n "$XMLFULL" ]]; then
+            echo -e "$XMLFULL | $COMMAND -"
+        else
+            echo -e "$COMMAND"
+        fi
         echo "---------------------------------------------------------"
     fi
     # expand the catalog
     [[ -n $CATALOG ]] && export XML_CATALOG_FILES="$XML_CATALOG_FILES $CATALOG"
-    eval "$COMMAND"
+    if [[ -n "$XMLFULL" ]]; then
+        eval "echo \"$XMLFULL\" | $COMMAND -"
+    else
+        eval "$COMMAND"
+    fi
+    
 else
     # resolve URNs
 #    if [[ urn: = ${STYLESHEET:0:4} ]]; then
 #        STYLESHEET=$(xmlcatalog $MAIN_CATALOG $STYLESHEET) || exit_on_error "The stylesheet is an URN which I cannot resolve using /etc/xml/catalog."
 #    fi
-    run-saxon "$PROCESSOR_ARGS $OUTPUT $XMLFILE $STYLESHEET ${PARMS[@]} ${STRPARMS[@]}"
+         run-saxon "$PROCESSOR_ARGS $OUTPUT $XMLFILE $STYLESHEET ${PARMS[@]} ${STRPARMS[@]}"
 fi
+
+#-----
+# Cleanup
+#
+if [[ -n $XML_TMP_FILE ]]; then
+    rm -f $XML_TMP_FILE
+fi
+
 
 exit;
 
